export const LOGIN_ACTION = "LOGIN_ACTION"
export const LOGOUT_ACTION = "LOGOUT_ACTION"
export const GET_LOGGED_USER_PROFILE_ACTION = "GET_LOGGED_USER_PROFILE_ACTION"
export const GET_ALL_USERS_ACTION = "GET_ALL_USERS_ACTION"